### PR TITLE
Add all part deux

### PR DESCRIPTION
**Pull request by johnhaley81**
An alternative PR to #22

Depends on #31

### CODE REVIEW

**Comment by sikanhe** [comment]
Any reason why this hasn't been added?

**Comment by gilbert** [comment]
I don't work with reasonml at the moment and haven't for a while. Does anyone want to become a maintainer?

**Comment by briangorman** [comment]
@gilbert I can help maintain this project

**Comment by gilbert** [comment]
@briangorman Invite sent

**Comment by briangorman** [comment]
@gilbert I reached out to you on your gitter about how to best proceed! Thanks

**Pull request merged**
