### PR TITLE
Run refmt on all files and replace |. with -> in docs and comments

### LINKED ISSUE #28: Format code using latest standards
I was wondering why the deprecated fast pipe operator (`|.`) is still being used in the docs and code. Is this to maintain backwards compatibility?

### PR DESCRIPTION
**Pull request by johnhaley81**
This fixes #28

### CODE REVIEW

**Comment by scull7** [comment]
:shipit: Looks good to me

**Comment by gilbert** [comment]
There are quite a lot of `->()` parenthesis. Are these actually necessary, or are they just precautions inserted by the refmt?

**Comment by johnhaley81** [comment]
Good eyes @gilbert. Those aren't needed and I removed them.

**Comment by gilbert** [comment]
Great, thank you!

**Pull request merged**
